<!--end .col --><!-- BEGIN MENUBAR-->
<div id="menubar" class="menubar-inverse  animate">

    <div class="menubar-fixed-panel">
        <div>
            <a class="btn btn-icon-toggle btn-default menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                <i class="fa fa-bars"></i>
            </a>
        </div>
        <div class="expanded">
            <a href="">
                <span class="text-lg text-bold text-primary ">Ur Buddy</span>
            </a>
        </div>
    </div>
    <div class="nano has-scrollbar" style="height: 216.007px;">
        <div class="nano-content" tabindex="0" style="right: -19px;">
            <div class="menubar-scroll-panel" style="padding-bottom: 33px;">

                <!-- BEGIN MAIN MENU -->
                <ul id="main-menu" class="gui-controls">

                    <!-- BEGIN DASHBOARD -->
                    <li class="active expanding">
                        <a href="home" class="active">
                            <div class="gui-icon"><i class="md md-home"></i></div>
                            <span class="title">Dashboard</span>
                        </a>
                    </li>
                    <!--end /menu-li -->
                    <!-- END DASHBOARD -->

                    <!-- BEGIN EMAIL -->
                    <li class="gui-folder">
                        <a>
                            <div class="gui-icon"><i class="md md-work"></i></div>
                            <span class="title">Catalog</span>
                        </a>
                        <!--start submenu -->
                        <ul style="">
                            <li class="gui-folder">
                            <li><a href="category.php"><span class="title">Manage Category</span></a></li>
                            <li><a href="manage-subcategory.php"><span class="title">Manage Subcategory</span></a></li>
                            <li><a href="manage-product.php"><span class="title">Product</span></a></li>
                            <li><a href="manage-top-products.php"><span class="title">Top Product</span></a></li>
                            <li><a href="Upload-bulk-product.php"><span class="title">Upload Bulk Product</span></a></li>
                            <li><a href="manage-brand.php"><span class="title">Brand</span></a></li>
                             <li><a href="manage-sizecategory.php"><span class="title">Size Category</span></a></li>
                              <li><a href="manage-size.php"><span class="title">Manage Size</span></a></li>

                        </ul>

                    </li>
                    <li class="gui-folder">
                        <a>
                            <div class="gui-icon"><i class="fa fa-archive"></i></div>
                            <span class="title">Extra</span>
                        </a>
                        <!--start submenu -->
                        <ul style="">
                    <li><a href="manage-offerbanner.php"><span class="title">Manage Offer's</span></a></li>
                    <li><a href="manage-discount.php"><span class="title">Manage Discount </span></a></li>
                    <li><a href="manage-coupan.php"><span class="title">Manage Coupan </span></a></li>
                   <li><a href="manage-review.php"><span class="title">Manage Review</span></a></li>    </ul>
                    </li>

                    <li class="gui-folder">
                        <a>
                            <div class="gui-icon"><i class="fa fa-database"></i></div>
                            <span class="title"> Banner's </span>
                        </a>
                        <ul style="">
                            <li class="gui-folder">
                            <li><a href="manage-banner.php"><span class="title">Manage Site Banner</span></a></li>
                            <li><a href="manage-offerbanner.php"><span class="title">Manage Offer's</span></a></li>

                        </ul>
                    </li>
                    <li class="gui-folder">
                        <a>
                            <div class="gui-icon"><i class="fa fa-database"></i></div>
                            <span class="title"> Service's </span>
                        </a>
                        <ul style="">
                            <li class="gui-folder">
                            <li><a href="manage-services.php"><span class="title">Manage Services</span></a></li>
                            
                        </ul>
                    </li>
                    <li class="gui-folder">
                        <a>
                            <div class="gui-icon"><i class="fa fa-archive"></i></div>
                            <span class="title">Inventory</span>
                        </a>
                        <!--start submenu -->
                        <ul style="">
                            <li><a href="manage-saleinventory.php"><span class="title">Sale Inventory</span></a></li>
                            <li><a href="manage-salereport.php"><span class="title">Sale Report</span></a></li>
                            <li><a href="manage-purchase-inventory.php"><span class="title">Manage Purchage Inventory </span></a></li>
                            </ul>
                    </li>

                    <li class="gui-folder">
                        <a>
                            <div class="gui-icon"> <i class="fa fa-shopping-cart"></i></div>
                            <span class="title"> Cart</span>
                        </a>
                        <ul style="">
                            <li><a href="manage-transaction.php"><span class="title">Manage Transaction</span></a></li>
                            <li><a href="manage-ordar.php"><span class="title">Manage Ordar</span></a></li>
                            <li><a href="Update-bulk-order.php"><span class="title">Update Bulk Order</span></a></li>
                            <li><a href="manage_invoice.php"><span class="title">Manage Invoice</span></a></li>

                            <li><a href="manage-client.php"><span class="title">Manage Client</span></a></li>
                        </ul>
                    </li>


                            <li class="gui-folder">
                        <a>
                            <div class="gui-icon"><i class="fa fa-gear"></i></div>
                            <span class="title"> Setting</span>
                        </a>
                        <ul style="">
                            <li class="gui-folder">
                            <li><a href="manage-system.php"><span class="title">System Setting</span></a></li>
                            <li><a href="cartsetting.php"><span class="title">Cart Setting</span></a></li>
                            <li><a href="manage-pages.php"><span class="title">Manage Pages</span></a></li>
                             <li><a href="manage-faq.php"><span class="title">Manage FAQ</span></a></li>

                        </ul>
                    </li>

                    <!--end /menu-li -->
                    <!-- END EMAIL -->





                </ul>
                <!--end .main-menu -->
                <!-- END MAIN MENU -->

                <div class="menubar-foot-panel">
                    <small class="no-linebreak hidden-folded">
                        <span class="opacity-75">Copyright © 2015</span> <strong>HBW GROUP </strong>
                    </small>
                </div>
            </div>
        </div>
        <div class="nano-pane" style="display: block;">
            <div class="nano-slider" style="height: 71px; transform: translate(0px, 0px);"></div>
        </div>
    </div>
    <!--end .menubar-scroll-panel-->
